[package]
name = "database"
version = "0.1.0"
authors = ["fabianboesiger <boesiger.fabian@outlook.com>"]
edition = "2018"

[dependencies]
serialize_derive = { path = "serialize_derive" }
store_derive = { path = "store_derive" }