[package]
name = "database"
version = "0.1.0"
authors = ["fabianboesiger <boesiger.fabian@outlook.com>"]
edition = "2018"

[dependencies]
bytes_derive = { path = "bytes_derive" }
store_derive = { path = "store_derive" }